"""NSE/BSE stock universe organised by sector and market cap."""

SECTORS: dict[str, list[str]] = {
    "Banking": [
        "HDFCBANK.NS", "ICICIBANK.NS", "SBIN.NS", "KOTAKBANK.NS", "AXISBANK.NS",
        "INDUSINDBK.NS", "BANDHANBNK.NS", "FEDERALBNK.NS", "IDFCFIRSTB.NS", "AUBANK.NS",
        "PNB.NS", "CANBK.NS", "BANKBARODA.NS", "UNIONBANK.NS", "RBLBANK.NS",
    ],
    "IT": [
        "TCS.NS", "INFY.NS", "WIPRO.NS", "HCLTECH.NS", "TECHM.NS",
        "LTIM.NS", "MPHASIS.NS", "PERSISTENT.NS", "COFORGE.NS", "OFSS.NS",
        "KPITTECH.NS", "TATAELXSI.NS", "HEXAWARE.NS",
    ],
    "Pharma": [
        "SUNPHARMA.NS", "DIVISLAB.NS", "CIPLA.NS", "DRREDDY.NS", "APOLLOHOSP.NS",
        "BIOCON.NS", "AUROPHARMA.NS", "TORNTPHARM.NS", "LUPIN.NS", "ALKEM.NS",
        "IPCALAB.NS", "GLENMARK.NS", "NATCOPHARM.NS",
    ],
    "Auto": [
        "MARUTI.NS", "TATAMOTORS.NS", "BAJAJ-AUTO.NS", "HEROMOTOCO.NS", "EICHERMOT.NS",
        "TVSMOTOR.NS", "ASHOKLEY.NS", "BALKRISIND.NS", "MRF.NS", "BOSCHLTD.NS",
        "MOTHERSON.NS", "EXIDEIND.NS", "AMARAJABAT.NS",
    ],
    "FMCG": [
        "HINDUNILVR.NS", "ITC.NS", "NESTLEIND.NS", "BRITANNIA.NS", "DABUR.NS",
        "COLPAL.NS", "GODREJCP.NS", "MARICO.NS", "EMAMILTD.NS", "TATACONSUM.NS",
        "VBL.NS", "RADICO.NS", "MCDOWELL-N.NS",
    ],
    "Metal": [
        "TATASTEEL.NS", "JSWSTEEL.NS", "HINDALCO.NS", "VEDL.NS", "COALINDIA.NS",
        "NMDC.NS", "SAIL.NS", "JINDALSTEL.NS", "NATIONALUM.NS", "WELCORP.NS",
        "APLAPOLLO.NS", "RATNAMANI.NS",
    ],
    "Energy": [
        "RELIANCE.NS", "ONGC.NS", "BPCL.NS", "GAIL.NS", "TATAPOWER.NS",
        "NTPC.NS", "POWERGRID.NS", "IOC.NS", "HPCL.NS", "ADANIGREEN.NS",
        "TORNTPOWER.NS", "CESC.NS", "RECLTD.NS", "PFC.NS",
    ],
    "Infra": [
        "LT.NS", "ADANIPORTS.NS", "ADANIENT.NS", "ULTRACEMCO.NS", "GRASIM.NS",
        "AMBUJACEM.NS", "ACC.NS", "SIEMENS.NS", "ABB.NS", "HAVELLS.NS",
        "BHEL.NS", "IRFC.NS", "RVNL.NS", "IRCON.NS",
    ],
    "Finance": [
        "BAJFINANCE.NS", "BAJAJFINSV.NS", "HDFCLIFE.NS", "SBILIFE.NS", "ICICIPRULI.NS",
        "MUTHOOTFIN.NS", "CHOLAFIN.NS", "MANAPPURAM.NS", "M&MFIN.NS", "LICIHSGFIN.NS",
        "SUNDARMFIN.NS", "ABCAPITAL.NS",
    ],
    "Realty": [
        "DLF.NS", "GODREJPROP.NS", "OBEROIRLTY.NS", "PRESTIGE.NS", "BRIGADE.NS",
        "PHOENIXLTD.NS", "SOBHA.NS", "MAHLIFE.NS",
    ],
    "Consumer": [
        "TITAN.NS", "ASIANPAINT.NS", "PIDILITIND.NS", "BERGEPAINT.NS", "WHIRLPOOL.NS",
        "VOLTAS.NS", "BLUESTARCO.NS", "CROMPTON.NS", "HAVELLS.NS",
    ],
    "Telecom": [
        "BHARTIARTL.NS", "IDEA.NS", "TTML.NS",
    ],
}

# Flatten to full universe (deduplicated)
_seen: set[str] = set()
FULL_UNIVERSE: list[str] = []
SYMBOL_SECTOR: dict[str, str] = {}

for _sector, _syms in SECTORS.items():
    for _s in _syms:
        if _s not in _seen:
            _seen.add(_s)
            FULL_UNIVERSE.append(_s)
            SYMBOL_SECTOR[_s] = _sector


# ── Nifty Index Universes ──────────────────────────────────────────────────────

def _dedup(lst: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for s in lst:
        if s not in seen:
            seen.add(s)
            out.append(s)
    return out


NIFTY_50: list[str] = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "ITC.NS", "SBIN.NS", "BHARTIARTL.NS", "KOTAKBANK.NS",
    "LT.NS", "AXISBANK.NS", "ASIANPAINT.NS", "MARUTI.NS", "NESTLEIND.NS",
    "TITAN.NS", "SUNPHARMA.NS", "BAJFINANCE.NS", "WIPRO.NS", "HCLTECH.NS",
    "ULTRACEMCO.NS", "BAJAJFINSV.NS", "TECHM.NS", "ONGC.NS", "POWERGRID.NS",
    "NTPC.NS", "COALINDIA.NS", "TATAMOTORS.NS", "TATASTEEL.NS", "JSWSTEEL.NS",
    "ADANIENT.NS", "ADANIPORTS.NS", "DIVISLAB.NS", "CIPLA.NS", "DRREDDY.NS",
    "EICHERMOT.NS", "GRASIM.NS", "HEROMOTOCO.NS", "HINDALCO.NS", "INDUSINDBK.NS",
    "BRITANNIA.NS", "APOLLOHOSP.NS", "BPCL.NS", "TATACONSUM.NS", "SBILIFE.NS",
    "HDFCLIFE.NS", "BAJAJ-AUTO.NS", "UPL.NS", "VEDL.NS", "M&M.NS",
]

NIFTY_NEXT_50: list[str] = [
    "SIEMENS.NS", "ABB.NS", "HAVELLS.NS", "PIDILITIND.NS", "BERGEPAINT.NS",
    "COLPAL.NS", "DABUR.NS", "GODREJCP.NS", "MARICO.NS", "EMAMILTD.NS",
    "TATAPOWER.NS", "ADANIGREEN.NS", "DMART.NS", "NAUKRI.NS", "INDIGO.NS",
    "GAIL.NS", "IOC.NS", "HPCL.NS", "RECLTD.NS", "PFC.NS",
    "IRFC.NS", "DLF.NS", "GODREJPROP.NS", "AMBUJACEM.NS", "ACC.NS",
    "SHRIRAMFIN.NS", "MUTHOOTFIN.NS", "CHOLAFIN.NS", "BAJAJHLDNG.NS", "OFSS.NS",
    "LTIM.NS", "MPHASIS.NS", "PERSISTENT.NS", "COFORGE.NS", "TVSMOTOR.NS",
    "LUPIN.NS", "TORNTPHARM.NS", "AUROPHARMA.NS", "BIOCON.NS", "ALKEM.NS",
    "TATAELXSI.NS", "KPITTECH.NS", "UNIONBANK.NS", "CANBK.NS", "PNB.NS",
    "BANKBARODA.NS", "IDFCFIRSTB.NS", "FEDERALBNK.NS", "AUBANK.NS", "SRF.NS",
]

NIFTY_MIDCAP_50: list[str] = [
    "POLYCAB.NS", "TRENT.NS", "IRCTC.NS", "ZOMATO.NS", "DELHIVERY.NS",
    "DIXON.NS", "INDIAMART.NS", "LTTS.NS", "MPHASIS.NS", "HEXAWARE.NS",
    "RBLBANK.NS", "BANDHANBNK.NS", "IPCALAB.NS", "GLENMARK.NS", "AJANTPHARM.NS",
    "LAURUS.NS", "GRANULES.NS", "ABCAPITAL.NS", "MANAPPURAM.NS", "M&MFIN.NS",
    "SUNDARMFIN.NS", "LICIHSGFIN.NS", "PRESTIGE.NS", "BRIGADE.NS", "SOBHA.NS",
    "PHOENIXLTD.NS", "OBEROIRLTY.NS", "BALKRISIND.NS", "MRF.NS", "BOSCHLTD.NS",
    "VOLTAS.NS", "BLUESTARCO.NS", "CROMPTON.NS", "NMDC.NS", "SAIL.NS",
    "NATIONALUM.NS", "WELCORP.NS", "APLAPOLLO.NS", "RATNAMANI.NS", "VBL.NS",
    "RADICO.NS", "MCDOWELL-N.NS", "CONCOR.NS", "CAMS.NS", "CDSL.NS",
    "ANGELONE.NS", "MOTILALOFS.NS", "KAJARIA.NS", "CERA.NS", "GREENPANEL.NS",
]

NIFTY_MIDCAP_100: list[str] = _dedup(NIFTY_MIDCAP_50 + [
    "JKCEMENT.NS", "RAMCOCEM.NS", "DALMIA.NS", "DEEPAKNTR.NS", "AARTI.NS",
    "NAVINFLUOR.NS", "VINATIORGA.NS", "ATUL.NS", "ASTRAL.NS", "SUPREMEIND.NS",
    "CUMMINS.NS", "THERMAX.NS", "ESCORTS.NS", "TIINDIA.NS", "FINOLEX.NS",
    "KFINTECH.NS", "BSE.NS", "IDFC.NS", "IIFL.NS", "MFSL.NS",
    "AAVAS.NS", "HOMEFIRST.NS", "APTUS.NS", "CREDITACC.NS", "UJJIVANSFL.NS",
    "EQUITASBNK.NS", "PFIZER.NS", "ABBOTINDIA.NS", "SANOFI.NS", "SPARC.NS",
    "METROPOLIS.NS", "LALPATHLAB.NS", "MAXHEALTH.NS", "FORTIS.NS", "NH.NS",
    "RELAXO.NS", "BATA.NS", "RAYMOND.NS", "TRIDENT.NS", "VARDHMAN.NS",
    "WELSPUNIND.NS", "TORNTPOWER.NS", "CESC.NS", "JSWENERGY.NS", "NHPC.NS",
    "SJVN.NS", "HUDCO.NS", "NBCC.NS", "IRCON.NS", "RVNL.NS",
])

NIFTY_MIDCAP_150: list[str] = _dedup(NIFTY_MIDCAP_100 + [
    "CYIENT.NS", "INTELLECT.NS", "ZENSAR.NS", "HAPPSTMNDS.NS", "MASTEK.NS",
    "MOTHERSON.NS", "EXIDEIND.NS", "AMARAJABAT.NS", "SUPRAJIT.NS", "GABRIEL.NS",
    "GRINDWELL.NS", "TIMKEN.NS", "SKF.NS", "ELGIEQUIP.NS", "ESAB.NS",
    "HINDCOPPER.NS", "MOIL.NS", "GMRAIRPORT.NS", "ADANIGAS.NS", "IGL.NS",
    "MGL.NS", "GUJGASLTD.NS", "PETRONET.NS", "MRPL.NS", "HPCL.NS",
    "BHEL.NS", "KEI.NS", "POLYPLEX.NS", "NILKAMAL.NS", "IGPL.NS",
    "SAREGAMA.NS", "NETWORK18.NS", "STARHEALTH.NS", "NIACL.NS", "GODIGIT.NS",
    "KAYNES.NS", "SYRMA.NS", "TANLA.NS", "ROUTE.NS", "RATEGAIN.NS",
    "IEX.NS", "POWMECH.NS", "INOXWIND.NS", "SUZLON.NS", "RPOWER.NS",
    "BIKAJI.NS", "PRATAAP.NS", "JYOTHYLAB.NS", "KRBL.NS", "TRIVENI.NS",
])

NIFTY_SMALLCAP_50: list[str] = [
    "DOMS.NS", "SENCO.NS", "IDEAFORGE.NS", "NAZARA.NS", "EASEMYTRIP.NS",
    "RAILTEL.NS", "MSTCLTD.NS", "HBLPOWER.NS", "LLOYDSME.NS", "STLTECH.NS",
    "ASTERDM.NS", "YATHARTH.NS", "KRSNAA.NS", "THYROCARE.NS", "POLYMED.NS",
    "MEDPLUS.NS", "JBCHEPHARM.NS", "SUVEN.NS", "ORCHPHARMA.NS", "SOLARA.NS",
    "SHARDACROP.NS", "COROMANDEL.NS", "IOLCP.NS", "GNFC.NS", "ALKYLAMINE.NS",
    "FINEORG.NS", "BALAMINES.NS", "BALRAMCHIN.NS", "DWARIKESH.NS", "RENUKA.NS",
    "EIDPARRY.NS", "GALAXYSURF.NS", "KPRMILL.NS", "ARVIND.NS", "SPORTKING.NS",
    "CERA.NS", "SOMANY.NS", "KAJARIA.NS", "GREENPANEL.NS", "NILKAMAL.NS",
    "HAWKINCOOK.NS", "PRESTIGE.NS", "AAVAS.NS", "HOMEFIRST.NS", "APTUS.NS",
    "REPCO.NS", "UJJIVANSFL.NS", "EQUITASBNK.NS", "SURYODAY.NS", "CREDITACC.NS",
]

NIFTY_SMALLCAP_100: list[str] = _dedup(NIFTY_SMALLCAP_50 + [
    "MAHINDCIE.NS", "SUBROS.NS", "ENDURANCE.NS", "SANDHAR.NS", "PRICOLLTD.NS",
    "GREAVESCOT.NS", "GREENPANEL.NS", "CENTURYPLY.NS", "ASTRAL.NS", "FINOLEX.NS",
    "VGUARD.NS", "ORIENTELEC.NS", "POLYCAB.NS", "VOLTAMP.NS", "TDPOWERSYS.NS",
    "WEBSOL.NS", "SWSOLAR.NS", "OLECTRA.NS", "UCOBANK.NS", "INDIANB.NS",
    "KARURVYSYA.NS", "DCBBANK.NS", "CONCORDBIO.NS", "WINDLAS.NS", "SPARC.NS",
    "SANOFI.NS", "PFIZER.NS", "ABBOTINDIA.NS", "JUBLPHARMA.NS", "RPGLIFE.NS",
    "PNCINFRA.NS", "HGINFRA.NS", "KNRCON.NS", "SADBHAV.NS", "GPPL.NS",
    "IRCTC.NS", "CONCOR.NS", "RITES.NS", "DELHIVERY.NS", "CARTRADE.NS",
    "RAYMOND.NS", "TRIDENT.NS", "KPRMILL.NS", "ARVIND.NS", "VARDHMAN.NS",
    "AETHER.NS", "ANURAS.NS", "LAURUS.NS", "GRANULES.NS", "AJANTPHARM.NS",
])

NIFTY_SMALLCAP_250: list[str] = _dedup(NIFTY_SMALLCAP_100 + [
    "TIMETECHNO.NS", "NIIT.NS", "MASTEK.NS", "XCHANGING.NS", "SAKSOFT.NS",
    "RSSOFTWARE.NS", "INTELLECT.NS", "ZENSAR.NS", "HAPPSTMNDS.NS", "CYIENT.NS",
    "INOXWIND.NS", "SUZLON.NS", "RPOWER.NS", "JPPOWER.NS", "NHPC.NS",
    "SJVN.NS", "TORNTPOWER.NS", "CESC.NS", "JSWENERGY.NS", "NPTC.NS",
    "STOVEKRAFT.NS", "WONDERLA.NS", "SAPPHIRE.NS", "BIKAJI.NS", "PRATAAP.NS",
    "HAWKINCOOK.NS", "JYOTHYLAB.NS", "BAJAJCON.NS", "GALAXYSURF.NS", "EIDPARRY.NS",
    "DALMIASUG.NS", "DHAMPUR.NS", "RENUKA.NS", "TRIVENI.NS", "BALRAMCHIN.NS",
    "DWARIKESH.NS", "UTTAMSUGAR.NS", "MAGADSUGAR.NS", "MAITHANALL.NS", "SARDA.NS",
    "SHYAMMET.NS", "RATNAMANI.NS", "APLAPOLLO.NS", "WELCORP.NS", "NATIONALUM.NS",
    "GRAPHITE.NS", "HINDCOPPER.NS", "MOIL.NS", "NMDC.NS", "TINPLATE.NS",
    "HBLPOWER.NS", "LLOYDSME.NS", "STLTECH.NS", "HFCL.NS", "TEJASNET.NS",
    "TANLA.NS", "ROUTE.NS", "RATEGAIN.NS", "EASEMYTRIP.NS", "NAZARA.NS",
    "RAILTEL.NS", "MSTCLTD.NS", "IDEAFORGE.NS", "DOMS.NS", "SENCO.NS",
    "KAYNES.NS", "SYRMA.NS", "AVALON.NS", "IEX.NS", "CDSL.NS",
    "KFINTECH.NS", "CAMS.NS", "BSE.NS", "ANGELONE.NS", "MOTILALOFS.NS",
    "METROPOLIS.NS", "LALPATHLAB.NS", "MAXHEALTH.NS", "FORTIS.NS", "NH.NS",
    "KRSNAA.NS", "YATHARTH.NS", "THYROCARE.NS", "POLYMED.NS", "MEDPLUS.NS",
    "ASTERDM.NS", "STARHEALTH.NS", "NIACL.NS", "GODIGIT.NS", "CONCORDBIO.NS",
    "ORCHPHARMA.NS", "SOLARA.NS", "WINDLAS.NS", "JBCHEPHARM.NS", "SUVEN.NS",
    "FINEORG.NS", "BALAMINES.NS", "ALKYLAMINE.NS", "NAVINFLUOR.NS", "VINATIORGA.NS",
    "SHARDACROP.NS", "COROMANDEL.NS", "IOLCP.NS", "GNFC.NS", "AARTI.NS",
    "PNCINFRA.NS", "HGINFRA.NS", "KNRCON.NS", "SADBHAV.NS", "IRCON.NS",
    "RVNL.NS", "NBCC.NS", "HUDCO.NS", "GPPL.NS", "RITES.NS",
    "IGL.NS", "MGL.NS", "GUJGASLTD.NS", "PETRONET.NS", "ADANIGAS.NS",
    "MRPL.NS", "CHENNPETRO.NS", "AEGISLOG.NS", "ORIENTELEC.NS", "VOLTAMP.NS",
    "TDPOWERSYS.NS", "WEBSOL.NS", "SWSOLAR.NS", "OLECTRA.NS", "VGUARD.NS",
    "CERA.NS", "SOMANY.NS", "KAJARIA.NS", "GREENPANEL.NS", "CENTURYPLY.NS",
    "RAYMOND.NS", "ARVIND.NS", "WELSPUNIND.NS", "SPORTKING.NS", "KPRMILL.NS",
    "REPCO.NS", "UJJIVANSFL.NS", "SURYODAY.NS", "SPANDANA.NS", "CREDITACC.NS",
    "UCOBANK.NS", "INDIANB.NS", "KARURVYSYA.NS", "DCBBANK.NS", "J&KBANK.NS",
    "MAHINDCIE.NS", "SUBROS.NS", "ENDURANCE.NS", "SANDHAR.NS", "GABRIEL.NS",
    "GREAVESCOT.NS", "ELGIEQUIP.NS", "ESAB.NS", "GRINDWELL.NS", "TIMKEN.NS",
    "SKF.NS", "SUPRAJIT.NS", "PRICOLLTD.NS", "CRAFTSMAN.NS", "MINDA.NS",
])

NIFTY_MICROCAP_250: list[str] = _dedup(NIFTY_SMALLCAP_250 + [
    "KORE.NS", "PARAS.NS", "DIVGI.NS", "BELSTAR.NS", "UGROCAP.NS",
    "ARIHANTCAP.NS", "NARNOLIA.NS", "MASFIN.NS", "EMKAY.NS", "GEOJITFSL.NS",
    "IFBIND.NS", "SAREGAMA.NS", "TIPS.NS", "NAZARA.NS", "NETWORK18.NS",
    "MAFATLAL.NS", "NILAINFRA.NS", "SIGACHI.NS", "PAUSHAK.NS", "RPGLIFE.NS",
    "SHARDAIN.NS", "PASUPTAC.NS", "VETO.NS", "BLKASHYAP.NS", "DALMIASUG.NS",
    "BAJAJHEAL.NS", "CLNINDIA.NS", "DOMS.NS", "BIKAJI.NS", "PRATAAP.NS",
    "SENCO.NS", "HAWKINCOOK.NS", "JYOTHYLAB.NS", "BAJAJCON.NS", "GALAXYSURF.NS",
    "IREDA.NS", "SJVN.NS", "NHPC.NS", "POWMECH.NS", "MSTCLTD.NS",
    "RAILTEL.NS", "RITES.NS", "IRCTC.NS", "CONCOR.NS", "DELHIVERY.NS",
    "CARTRADE.NS", "EASEMYTRIP.NS", "RATEGAIN.NS", "ROUTE.NS", "TANLA.NS",
    "KAYNES.NS", "SYRMA.NS", "AVALON.NS", "IDEAFORGE.NS", "CENTUM.NS",
    "MASTEK.NS", "NIIT.NS", "TIMETECHNO.NS", "SAKSOFT.NS", "ZENSAR.NS",
    "HAPPSTMNDS.NS", "INTELLECT.NS", "CYIENT.NS", "STLTECH.NS", "HFCL.NS",
    "LLOYDSME.NS", "HBLPOWER.NS", "OLECTRA.NS", "INOXWIND.NS", "SUZLON.NS",
    "JPPOWER.NS", "RPOWER.NS", "SWSOLAR.NS", "WEBSOL.NS", "TDPOWERSYS.NS",
    "VOLTAMP.NS", "ORIENTELEC.NS", "VGUARD.NS", "KEI.NS", "FINOLEX.NS",
    "SOMANY.NS", "CERA.NS", "GREENPANEL.NS", "CENTURYPLY.NS", "STYLAM.NS",
    "ARVINDFASN.NS", "SPORTKING.NS", "HIMATSEIDE.NS", "TRIDENT.NS", "WELSPUNIND.NS",
    "DWARIKESH.NS", "DALMIASUG.NS", "DHAMPUR.NS", "UTTAMSUGAR.NS", "MAGADSUGAR.NS",
    "IOLCP.NS", "GNFC.NS", "ALKYLAMINE.NS", "FINEORG.NS", "BALAMINES.NS",
    "POLYMED.NS", "THYROCARE.NS", "KRSNAA.NS", "YATHARTH.NS", "CONCORDBIO.NS",
    "ORCHPHARMA.NS", "WINDLAS.NS", "SUVEN.NS", "JBCHEPHARM.NS", "RPGLIFE.NS",
    "PNCINFRA.NS", "HGINFRA.NS", "KNRCON.NS", "SADBHAV.NS", "GPPL.NS",
    "MAHINDCIE.NS", "SANDHAR.NS", "GABRIEL.NS", "SUBROS.NS", "PRICOLLTD.NS",
    "MINDA.NS", "SUPRAJIT.NS", "CRAFTSMAN.NS", "ENDURANCE.NS", "GREAVESCOT.NS",
])

# ── Derived composite indices ──────────────────────────────────────────────────

NIFTY_100: list[str]             = _dedup(NIFTY_50 + NIFTY_NEXT_50)
NIFTY_200: list[str]             = _dedup(NIFTY_100 + NIFTY_MIDCAP_100)
NIFTY_LARGEMIDCAP_250: list[str] = _dedup(NIFTY_100 + NIFTY_MIDCAP_150)
NIFTY_500: list[str]             = _dedup(NIFTY_200 + NIFTY_MIDCAP_150 + NIFTY_SMALLCAP_250)

# ── Index registry (used by research API & frontend) ──────────────────────────

NIFTY_INDICES: dict[str, dict] = {
    "nifty50":             {"label": "NIFTY 50",              "cap": "Large Cap",  "symbols": NIFTY_50},
    "nifty_next50":        {"label": "NIFTY Next 50",         "cap": "Large Cap",  "symbols": NIFTY_NEXT_50},
    "nifty100":            {"label": "NIFTY 100",             "cap": "Large Cap",  "symbols": NIFTY_100},
    "nifty200":            {"label": "NIFTY 200",             "cap": "Broad",      "symbols": NIFTY_200},
    "nifty500":            {"label": "NIFTY 500",             "cap": "Broad",      "symbols": NIFTY_500},
    "nifty_midcap50":      {"label": "NIFTY Midcap 50",       "cap": "Mid Cap",    "symbols": NIFTY_MIDCAP_50},
    "nifty_midcap100":     {"label": "NIFTY Midcap 100",      "cap": "Mid Cap",    "symbols": NIFTY_MIDCAP_100},
    "nifty_midcap150":     {"label": "NIFTY Midcap 150",      "cap": "Mid Cap",    "symbols": NIFTY_MIDCAP_150},
    "nifty_largemidcap250":{"label": "NIFTY LargeMidcap 250", "cap": "Mid Cap",    "symbols": NIFTY_LARGEMIDCAP_250},
    "nifty_smallcap50":    {"label": "NIFTY Smallcap 50",     "cap": "Small Cap",  "symbols": NIFTY_SMALLCAP_50},
    "nifty_smallcap100":   {"label": "NIFTY Smallcap 100",    "cap": "Small Cap",  "symbols": NIFTY_SMALLCAP_100},
    "nifty_smallcap250":   {"label": "NIFTY Smallcap 250",    "cap": "Small Cap",  "symbols": NIFTY_SMALLCAP_250},
    "nifty_microcap250":   {"label": "NIFTY Microcap 250",    "cap": "Micro Cap",  "symbols": NIFTY_MICROCAP_250},
}
