apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mts

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres/pvc.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - mongodb/pvc.yaml
  - mongodb/deployment.yaml
  - mongodb/service.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - ingress.yaml
  - monitoring/kube-state-metrics/rbac.yaml
  - monitoring/kube-state-metrics/deployment.yaml
  - monitoring/kube-state-metrics/service.yaml
  - monitoring/node-exporter/daemonset.yaml
