"""Watchlist Pick History — tracks price/P&L over time for every pick
generated by the Stock of the Day, BTST, and Golden Stock ("Intraday")
engines, so each pick's performance since the day it was announced can be
viewed day-by-day, week-by-week, or month-by-month.

Deliberately decoupled from stock_of_day/btst/golden_stock's own domain
models and services -- this only *reads* their already-generated picks
(see watchlist_history_service.ingest_todays_picks) and keeps its own
independent record, one document per pick occurrence (a symbol picked again
later gets its own new entry here, not an update to the earlier one).
"""

from dataclasses import dataclass, field
from datetime import datetime

# Number of daily EOD job runs a pick is tracked for before it freezes.
# Stored per-document (WatchlistHistoryPick.window_days) at creation time so
# changing this constant later never retroactively alters an already-frozen
# pick's tracking window.
WATCHLIST_HISTORY_WINDOW_DAYS = 30

WATCHLIST_HISTORY_SOURCES = ("SOTD", "BTST", "GOLDEN_STOCK")


@dataclass
class WatchlistHistorySnapshot:
    date: str  # "YYYY-MM-DD" IST -- the trading day this snapshot represents
    trading_day_number: int  # 0 = announce-day EOD snapshot, 1 = next run, ...
    price: float
    pnl_pct: float  # (price - buy_price) / buy_price * 100
    captured_at: datetime


@dataclass
class WatchlistHistoryPick:
    source: str  # "SOTD" | "BTST" | "GOLDEN_STOCK"
    symbol: str
    name: str
    sector: str
    announced_date: str  # "YYYY-MM-DD" IST -- immutable key component
    announced_at: str  # ISO datetime from the source doc
    buy_price: float  # entry_price captured once at ingestion, never mutated again
    stop_loss: float | None = None
    target: float | None = None
    source_ref_id: str | None = None  # id of the underlying source doc, for traceability
    source_score: float | None = None  # composite_score (SotD) or confidence_score (BTST/Golden Stock)

    window_days: int = WATCHLIST_HISTORY_WINDOW_DAYS
    trading_day_count: int = 0  # increments every EOD job run attempted, success or not
    frozen: bool = False
    frozen_at: str | None = None
    freeze_reason: str | None = None  # "WINDOW_COMPLETE" (only reason in this scope)

    last_price: float | None = None
    last_pnl_pct: float | None = None
    last_snapshot_date: str | None = None  # also the daily-job idempotency guard

    snapshots: list[WatchlistHistorySnapshot] = field(default_factory=list)
    created_at: datetime | None = None
    updated_at: datetime | None = None
    id: str | None = field(default=None, compare=False)
