// Ticker -> company name lookup for the USA Stocks "Add stock" autocomplete
// only -- a static, curated list of well-known NASDAQ/NYSE names so typing
// shows sensible suggestions. Not the source of truth for what's tracked
// (that's usa_stocks_service.TRACKED_STOCKS + custom additions on the
// backend); any ticker can still be typed and added even if it's not in
// this list, it just won't show up in the dropdown while typing.
export type UsaStockDirectoryEntry = { code: string; name: string }

export const USA_STOCK_DIRECTORY: UsaStockDirectoryEntry[] = [
  { code: 'AAPL', name: 'Apple Inc.' },
  { code: 'MSFT', name: 'Microsoft Corporation' },
  { code: 'GOOGL', name: 'Alphabet Inc. (Class A)' },
  { code: 'GOOG', name: 'Alphabet Inc. (Class C)' },
  { code: 'AMZN', name: 'Amazon.com Inc.' },
  { code: 'NVDA', name: 'NVIDIA Corporation' },
  { code: 'META', name: 'Meta Platforms Inc.' },
  { code: 'TSLA', name: 'Tesla Inc.' },
  { code: 'BRK-B', name: 'Berkshire Hathaway Inc. (Class B)' },
  { code: 'LLY', name: 'Eli Lilly and Company' },
  { code: 'AVGO', name: 'Broadcom Inc.' },
  { code: 'JPM', name: 'JPMorgan Chase & Co.' },
  { code: 'V', name: 'Visa Inc.' },
  { code: 'UNH', name: 'UnitedHealth Group Incorporated' },
  { code: 'XOM', name: 'Exxon Mobil Corporation' },
  { code: 'MA', name: 'Mastercard Incorporated' },
  { code: 'JNJ', name: 'Johnson & Johnson' },
  { code: 'PG', name: 'Procter & Gamble Company' },
  { code: 'HD', name: 'Home Depot Inc.' },
  { code: 'COST', name: 'Costco Wholesale Corporation' },
  { code: 'MRK', name: 'Merck & Co. Inc.' },
  { code: 'ABBV', name: 'AbbVie Inc.' },
  { code: 'CVX', name: 'Chevron Corporation' },
  { code: 'CRM', name: 'Salesforce Inc.' },
  { code: 'BAC', name: 'Bank of America Corporation' },
  { code: 'PEP', name: 'PepsiCo Inc.' },
  { code: 'KO', name: 'Coca-Cola Company' },
  { code: 'ADBE', name: 'Adobe Inc.' },
  { code: 'WMT', name: 'Walmart Inc.' },
  { code: 'NFLX', name: 'Netflix Inc.' },
  { code: 'AMD', name: 'Advanced Micro Devices Inc.' },
  { code: 'TMO', name: 'Thermo Fisher Scientific Inc.' },
  { code: 'MCD', name: "McDonald's Corporation" },
  { code: 'LIN', name: 'Linde plc' },
  { code: 'CSCO', name: 'Cisco Systems Inc.' },
  { code: 'ABT', name: 'Abbott Laboratories' },
  { code: 'ACN', name: 'Accenture plc' },
  { code: 'ORCL', name: 'Oracle Corporation' },
  { code: 'DIS', name: 'Walt Disney Company' },
  { code: 'PM', name: 'Philip Morris International Inc.' },
  { code: 'WFC', name: 'Wells Fargo & Company' },
  { code: 'DHR', name: 'Danaher Corporation' },
  { code: 'VZ', name: 'Verizon Communications Inc.' },
  { code: 'TXN', name: 'Texas Instruments Incorporated' },
  { code: 'INTU', name: 'Intuit Inc.' },
  { code: 'AMGN', name: 'Amgen Inc.' },
  { code: 'CAT', name: 'Caterpillar Inc.' },
  { code: 'IBM', name: 'International Business Machines Corporation' },
  { code: 'GE', name: 'General Electric Company' },
  { code: 'NOW', name: 'ServiceNow Inc.' },
  { code: 'QCOM', name: 'QUALCOMM Incorporated' },
  { code: 'MU', name: 'Micron Technology Inc.' },
  { code: 'UBER', name: 'Uber Technologies Inc.' },
  { code: 'LYFT', name: 'Lyft Inc.' },
  { code: 'SBUX', name: 'Starbucks Corporation' },
  { code: 'INTC', name: 'Intel Corporation' },
  { code: 'PYPL', name: 'PayPal Holdings Inc.' },
  { code: 'BA', name: 'Boeing Company' },
  { code: 'NKE', name: 'Nike Inc.' },
  { code: 'GS', name: 'Goldman Sachs Group Inc.' },
  { code: 'MS', name: 'Morgan Stanley' },
  { code: 'C', name: 'Citigroup Inc.' },
  { code: 'AXP', name: 'American Express Company' },
  { code: 'BLK', name: 'BlackRock Inc.' },
  { code: 'SPGI', name: 'S&P Global Inc.' },
  { code: 'T', name: 'AT&T Inc.' },
  { code: 'CMCSA', name: 'Comcast Corporation' },
  { code: 'PFE', name: 'Pfizer Inc.' },
  { code: 'UPS', name: 'United Parcel Service Inc.' },
  { code: 'RTX', name: 'RTX Corporation' },
  { code: 'LOW', name: "Lowe's Companies Inc." },
  { code: 'HON', name: 'Honeywell International Inc.' },
  { code: 'UNP', name: 'Union Pacific Corporation' },
  { code: 'ELV', name: 'Elevance Health Inc.' },
  { code: 'BKNG', name: 'Booking Holdings Inc.' },
  { code: 'DE', name: 'Deere & Company' },
  { code: 'SBAC', name: 'SBA Communications Corporation' },
  { code: 'MDT', name: 'Medtronic plc' },
  { code: 'ADI', name: 'Analog Devices Inc.' },
  { code: 'GILD', name: 'Gilead Sciences Inc.' },
  { code: 'ISRG', name: 'Intuitive Surgical Inc.' },
  { code: 'REGN', name: 'Regeneron Pharmaceuticals Inc.' },
  { code: 'VRTX', name: 'Vertex Pharmaceuticals Incorporated' },
  { code: 'PLTR', name: 'Palantir Technologies Inc.' },
  { code: 'SNOW', name: 'Snowflake Inc.' },
  { code: 'SHOP', name: 'Shopify Inc.' },
  { code: 'SQ', name: 'Block Inc.' },
  { code: 'ABNB', name: 'Airbnb Inc.' },
  { code: 'COIN', name: 'Coinbase Global Inc.' },
  { code: 'RIVN', name: 'Rivian Automotive Inc.' },
  { code: 'F', name: 'Ford Motor Company' },
  { code: 'GM', name: 'General Motors Company' },
  { code: 'DAL', name: 'Delta Air Lines Inc.' },
  { code: 'UAL', name: 'United Airlines Holdings Inc.' },
  { code: 'MAR', name: 'Marriott International Inc.' },
  { code: 'YUM', name: 'Yum! Brands Inc.' },
  { code: 'CL', name: 'Colgate-Palmolive Company' },
  { code: 'MO', name: 'Altria Group Inc.' },
  { code: 'SO', name: 'Southern Company' },
  { code: 'DUK', name: 'Duke Energy Corporation' },
  { code: 'NEE', name: 'NextEra Energy Inc.' },
  { code: 'MMM', name: '3M Company' },
  { code: 'FDX', name: 'FedEx Corporation' },
]
